### ISSUE TITLE
Legend/Layers in tabs

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/angular2-esri-example#10]
Once #7 is merged, it would be nice if the app could show both legend and the layer list. Could use tabs. There are [a few standalone implementations](http://juristr.com/blog/2016/02/learning-ng2-creating-tab-component/) that could work. However, it would probably be more instructive to try and use [bootstrap](http://valor-software.com/ng2-bootstrap/)

**Comment by Shawn-Fan** [comment]
You mean put the legend and layer list in the tab control? I can try it. Originally I want to use Angular2 material to do layer selection(checkbox lists) , I also notice that the "tab control" will be published recently, Do you think it is a good idea to use angular2 material  or do it in the ways you mentioned?

**Comment by tomwayson** [comment]
For now I've placed the legend in a scrollable container so all components are visible on the page.

![image](https://cloud.githubusercontent.com/assets/662944/15131878/ae1d001a-1608-11e6-9d1a-f2523cce0a5f.png)

I think generally speaking material design is fine. However, for this repo, I'm more interested in using Bootstrap for compatibility w/ [calcite bootstrap](https://github.com/Esri/calcite-bootstrap).

**Comment by Shawn-Fan** [comment]
Calcite bootstrap looks like a UI library from ESRI, hope use it in the future.
By the way, do you have any "spatial function" development plan in the future?

**Comment by tomwayson** [comment]
I don't have any plans to develop spatial functions for this repo. My entire roadmap can be seen in the [issues](https://github.com/tomwayson/angular2-esri-example/issues), and even for those I have no timeline as this is just a side project.

**Comment by tomwayson** [comment]
resolved in #20
