### ISSUE TITLE
Map using local services & basemap

### ISSUE THREAD

**Issue by dimpyvirk** [tomwayson/angular2-esri-example#11]
In the code you used ‘esri/arcgis/utils’ to create map (https://developers.arcgis.com/javascript/3/jsapi/esri.arcgis.utils-amd.html). Is it possible to create map using “Map” object  https://developers.arcgis.com/javascript/3/jsapi/map-amd.html” so that base map and other layers are from local server instead of Esri server.
I want to use local published services.

**Comment by tomwayson** [comment]
Of course.

First, it's possible to create a web map that points to local services and then save that web map to your own portal or ArcGIS Online. You could do that and not have to change any code here.

Alternatively, f you wanted to create a map using `new Map(...)`, you'd just need to include the modules for the map and whatever layer types you're going to use in the call to `esriSystem.register()` in index.html. For example:

```
    esriSystem.register([
      'esri/map',
      'esri/layers/FeatureLayer',
      'esri/basemaps',
      'esri/dijit/Legend',
      'esri/dijit/Search'
    ], function () {
      // then bootstrap application
      System.import('app/boot')
        .then(null, console.error.bind(console));
    }, {
      moduleNameOverrides: {
        'esri/map': 'Map',
        'esri/basemaps': 'esriBasemaps'
      }
    });
```

and then in your .ts code:

``` ts
import { Map, FeatureLayer, esriBasemaps, Legend, Search } from 'esri';
```

**Comment by tomwayson** [comment]
Closing this assuming the above worked for you. If not, you can re-open.
