### ISSUE TITLE
Problem using esri library w/ angular-cli

### ISSUE THREAD

**Issue by vivekimsit** [tomwayson/angular2-esri-example#16]
Hi,

I am trying to load with [angular-cli](https://github.com/angular/angular-cli) but no luck, it can't find `esri` module, can you please help me to identify where top put the dependencies.

**Comment by tomwayson** [comment]
I have not tried angular-cli yet, but I would suspect that _at the very least_ you'd have to modify the webpack.config.js as follows:
1. [Exclude esri/dojo modules](https://github.com/tomwayson/angular2-esri-example/blob/feda3136f2a4edc821186f98f48977ec61b23628/webpack.config.js#L53-L64)
2. [Specify 'amd' as the target module format](https://github.com/tomwayson/angular2-esri-example/blob/feda3136f2a4edc821186f98f48977ec61b23628/webpack.config.js#L28)

**Comment by tomwayson** [comment]
You can see an example of how to use the ArcGIS API for JavaScript in an angular-cli project here: https://github.com/tomwayson/angular-cli-esri

**Comment by tomwayson** [comment]
More info about how the above project works is available here: http://tomwayson.com/2016/11/27/using-the-arcgis-api-for-javascript-in-applications-built-with-webpack/

I'm going to close this issue as I have no intent to use angular-cli in this repo and there are other ways to use to use the ArcGIS API w/ angular-cli.

**Comment by tomwayson** [comment]
Update: http://disq.us/p/1gbqtt3
