### ISSUE TITLE
Can't add event listeners

### ISSUE THREAD

**Issue by Rshalika** [tomwayson/angular2-esri-example#18]
Hi,

I just tried your example and it is really good, but I wanted to listen to the click event on the map and couldn't manage . 

I am doing this 
in onMapLoad : 
`map.on( "click",  listener  )  ;
    function listener (evt){
      alert("click")
    }
`
but it has no effect. **I want to add event listeners on single graphics also**

**Comment by tomwayson** [comment]
can you try that by inlining the named function instead of referencing it?

```
map.on( "click", function listener (evt){ alert("click") } ) ; 
```

**Comment by Rshalika** [comment]
I have tried it. Did not  work.

**Comment by tomwayson** [comment]
I added the following:

``` ts
    // add click handler to map
    map.on('click', function(e) {
      console.log(e);
    });
```

Immediately after the [`const map = response.map;` line in master](https://github.com/tomwayson/angular2-esri-example/blob/feda3136f2a4edc821186f98f48977ec61b23628/app/app.component.ts#L61), and I see the event object logged to the console ever time I click on the map.

**Comment by Rshalika** [comment]
this works on your particular map , but when I try to change the map (change map id)  it stops working

**Comment by Rshalika** [comment]
Well, my map did not have any layers and so on, which you were using in this example. I removed all functionality that  caused the error because of that and click worked. 
thanks
