### ISSUE TITLE
Update to RC6

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/angular2-esri-example#25]
https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes

**Comment by eddiepantoja** [comment]
I [modified 4 files](https://github.com/tomwayson/angular2-esri-example/commit/7d8314b250e6321126dcf6d816410d63625dcc7a) to update to RC6.
- package.json
- systemjs.config.js
- tsconfig.json
- webpack.config.js

**Comment by tomwayson** [comment]
Thanks!

Closed in 7d8314b250e6321126dcf6d816410d63625dcc7a
