### ISSUE TITLE
angularclass webpack and jsapi

### ISSUE THREAD

**Issue by hassanqaiser** [tomwayson/angular2-esri-example#27]
Would you please advise how I can load arc-js-api and dojo modules in angular2-webpack-starter in the link below,

https://github.com/AngularClass/angular2-webpack-starter

Thanks,
Qaiser

**Comment by dyh333** [comment]
@hassanqaiser i am trying this also, if success, tell me how. thanks.
and you can see this issue #26 , hope can help you.

**Comment by tomwayson** [comment]
@dyh333 

@hassanqaiser has forked the Angular Class webpack starter and updated it to use the ArcGIS API for JavaScript. His repo can be found here:

https://github.com/hassanqaiser/angular2_webpack2_esri

**Comment by tomwayson** [comment]
Another way to integrate the ArcGIS API for JavaScript into the Angular Class starter would be to use the [angular2-esri-loader](https://github.com/tomwayson/angular2-esri-loader) library and follow the "dedicated loader pattern" described in [this blog post](http://tomwayson.com/2016/11/27/using-the-arcgis-api-for-javascript-in-applications-built-with-webpack/).

**Comment by dyh333** [comment]
@tomwayson  thanks, i will try it.
