### ISSUE TITLE
Angular 2 RTM

### ISSUE THREAD

**Issue by klanglie** [tomwayson/angular2-esri-example#29]
I was curious if you plan on updating this project to use Angular 2 RTM?

**Comment by tomwayson** [comment]
@eddiepantoja already did https://github.com/tomwayson/angular2-esri-example/commit/e8bd68b685c66a5562a3493851e5bae322a2b8f0

I just need to [cut a release](https://github.com/tomwayson/angular2-esri-example/releases).

**Comment by tomwayson** [comment]
Resolved in https://github.com/tomwayson/angular2-esri-example/commit/b40d9cec4289392e6411ee38997bd56e115e987a
