### ISSUE TITLE
Core-js && reflect-metadata packages

### ISSUE THREAD

**Issue by argiropoulostauros** [tomwayson/angular2-esri-example#30]
I think reflect-metadata is unnecessary and core-js provides a reflect api.
Great job!

**Comment by tomwayson** [comment]
Thanks @argiropoulostauros! 

Interesting to know that it may work w/o that, but we've been following the dependencies listed in the [Angualr 2 TS Quickstart](https://angular.io/docs/ts/latest/quickstart.html#!#install-packages) and probably will continue to do so unless dropping reflect-metadata is a norm in the community.

**Comment by argiropoulostauros** [comment]
@tomwayson ok that sounds good.
