### ISSUE TITLE
how to put a angular component into a map infowindow

### ISSUE THREAD

**Issue by dyh333** [tomwayson/angular2-esri-example#35]
hi, @tomwayson. I recently met a new problem. In some case, a map infowindow may be complex, so I want to create a ng2 component to define the infowindow content. the question is how can I put this compnent into the infowindow? 

any help is much appreciated!  thanks.

**Comment by dyh333** [comment]
@odoe @lobsteropteryx @jwasilgeo  any help is much appreciated! thanks.

**Comment by tomwayson** [comment]
My advice would be to not use an info window. If the content is that complex, something that you can't/don't want to handle w/ the ArcGIS API's own templating and/or widgets, then I would suggest handling the feature select/click events and opening the component somewhere else on the screen (along side the map, in a modal, etc). Where would depend on things like the layout of the view containing the map, what kind of mobile support you require, etc.

I'm not saying you can't do it w/ a popup. You probably can handle the map's popup shown event, and mount a component to something like an empty div in the popup's content. However, you're going to spend a lot of effort managing the widget/component lifecycles. The specifics would depend on what version of the ArcGIS API you're using.

**Comment by dyh333** [comment]
thanks your advice, I will try it.  by the way, I google a similar question which link is http://stackoverflow.com/questions/38614305/angular-2-insert-dom-into-infowindow-element-that-was-created-by-google-maps-v3
unfortunately I am a new starter of ng2.  do you think dynamic create component and insert into infowindow can work?  thanks.

**Comment by tomwayson** [comment]
The approach outlined in that SO answer _should_ work for an ArcGIS info window, or at least work as well as it would for a Google Maps info window. However, that code already looks complicated, and it doesn't even deal w/ handling the map event that would call that code, or how to communicate from that component to the rest of the angular app and/or the map, nor how to destroy the component you created on the fly. That all might be trivial, or it might be a mess.

Personally, if at all possible I would still prefer to have the map component emit an event that a feature has been clicked or selected and pass the feature data to angular and let it render the "info window" content into the component tree that it already controls (outside the map).
