### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by Abexdatl** [tomwayson/angular2-esri-example#37]
I found this sample very useful , especially the use of webpack. 

However I am facing an issue when i do npm install after cloning . 

P.S,  this is happening on a corporate network only. I dot have this issue on my personal machine outside of the corporate network. see the console output below for more info , any idea ? 

> typings install

typings WARN badlocation "github:Esri/jsapi-resources/3.x/typescript/arcgis-js-a
pi.d.ts" is mutable and may change, consider specifying a commit hash
typings WARN deprecated 9/14/2016: "registry:dt/core-js#0.0.0+20160524134847" is
 deprecated (updated, replaced or removed)
typings WARN deprecated 9/7/2016: "registry:dt/dojo#1.9.0+20160521151917" is dep
recated (updated, replaced or removed)
typings ERR! message Unable to connect to "https://raw.githubusercontent.com/Esr
i/jsapi-resources/master/3.x/typescript/arcgis-js-api.d.ts"
typings ERR! caused by self signed certificate in certificate chain
typings ERR!

npm ERR! code ELIFECYCLE
npm ERR! angular2-esri-example@0.2.4 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-esri-example@0.2.4 postinstall script 'typings i
nstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-esri-example
 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-esri-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-esri-example

**Comment by tomwayson** [comment]
@Abexdatl I'm glad you found this useful, and I'm sorry that you're having that install issue.

Looks like your corporate firewall doesn't like the cert on https://raw.githubusercontent.com/Esr
i/jsapi-resources/master/3.x/typescript/arcgis-js-api.d.ts

However, I no longer use Angular (no TypeScript) day to day, so I'm not sure if the way this repository is getting the types is the most up to date way.

You might try [installing them via npm as documented here](https://github.com/Esri/jsapi-resources/tree/master/3.x/typescript#typescript).

Although I'm [not actively maintaining this repository](https://github.com/tomwayson/angular2-esri-example#status), if you do find a better way to install the types I'd gladly accept a pull request.
