### ISSUE TITLE
Update to Angular 2 RC

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/angular2-esri-example#8]
See https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc0-2016-05-02

**Comment by Shawn-Fan** [comment]
I try to update the project to Angular 2 RC, it looks like the library loading method is different from before. Should I just put "Configure and load Esri libraries" same as before(in index.html file)? or in the systemjs.config.js file?

**Comment by tomwayson** [comment]
To be honest, I haven't had a chance to look into it yet, and don't have any time to in the immediate future, but it would be great if you can get it working. I'll let you decide which approach works best and make a pull request. Thanks!

**Comment by Shawn-Fan** [comment]
Thanks, I 'll try to figure it out...

**Comment by Shawn-Fan** [comment]
It works in Angular2 RC1 and I'll update soon

**Comment by tomwayson** [comment]
Nice work! I'm looking forward to the pull request.

**Comment by Shawn-Fan** [comment]
something wrong? pull request is gone

**Comment by tomwayson** [comment]
It looks like you closed it. Based on your comment above, I'm going to assume by accident, so I will re-open it. If you had a reason to close it (like you are going to make new pull request w/ the same functionality), you can close it again and leave a comment there w/ your reason.

**Comment by tomwayson** [comment]
Resolved in #12

**Comment by Shawn-Fan** [comment]
Great, it works
